### ISSUE TITLE
Y'all should fork this repo for yourselves

### ISSUE THREAD

**Issue by pastly** [Deedasmi/cdcdb-webserver#146]
If you want to show it off, that is. I can't make promises that it will stay right here at pastly/cdcdb-webserver forever. Realistically, it will. But still.

Plus then it will be on your profile and associated with you.

Assigning you all so you get notifications.

**Comment by Deedasmi** [comment]
Could you just transfer ownership of both repos to me?

**Comment by pastly** [comment]
That would work too. Then everyone (including me) should fork that if they want to show it off.

The CDC github account doesn't want to own this?

**Comment by Deedasmi** [comment]
We have an argus labs account, no CDC account. Working on git infrastructure over winter break.

**Comment by pastly** [comment]
@Deedasmi let's plan on transferring ownership of these repos to you after grades are finalized. 

@Deedasmi if you want help setting up self-hosted (with CDC hardware) git infrastructure, I'd gladly help.

**Comment by flemingcaleb** [comment]
@pastly I might take you up on that offer for help

Caleb Fleming
Kansas State University
President AAIA UAS Design Team
Treasurer Cyber Defense Club

Sent from my iPhone

On Dec 11, 2016, at 14:33, Matt Traudt <notifications@github.com<mailto:notifications@github.com>> wrote:


@Deedasmi<https://github.com/Deedasmi> let's plan on transferring ownership of these repos to you after grades are finalized.

@Deedasmi<https://github.com/Deedasmi> if you want help setting up self-hosted (with CDC hardware) git infrastructure, I'd gladly help.

-

**Comment by pastly** [comment]
Transferred to Richard. Closing issue.
